### ISSUE TITLE
can the client be use for other servers, like rcbranch ?

### ISSUE THREAD

**Issue by egonw** [wikipathways/wikipathways-api-client-java#11]
This came up because it would allow us to create RDF for content only on the rcbranch server, allowing us to run JUnit tests on the RDF for, for example, Reactome content up there...

**Comment by mkutmon** [comment]
Yes in PathVisio you can change the URL in the preferences. In de code you can give the URL when you create the client.

**Comment by egonw** [comment]
But that requires me to know the "webservice" of the rcbranch server, not? I can see where I should replace "http://webservice.wikipathways.org", but how I can I discover what that should be http://rcbranch.wikipathways.org/ ?
