### ISSUE TITLE
Update for https?

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/wikipathways-api-client-java#13]
Ok. Looks like the WP plugin for PV no longer works when the site is HTTPS. Is this api-client-java lib the suspect?

I see Egon's test fix here:
https://github.com/wikipathways/wikipathways-api-client-java/commit/cc55bf8b592009701d8b88c109a0e062f696d069

However, the old link should work fine, as it just get's redirected to https:
http://webservice.wikipathways.org

I would suggest reverting this...

**Comment by AlexanderPico** [comment]
Oh, I just looked at the commit again...  The change was just http to https, the URL has always been to rcbranch.wikipathways.org/wpi/webservicetest.  

This explains why the test is failing. The updated ConnectionSettings test should use:
http://webservice.wikipathways.org

**Comment by nunogit** [comment]
Hello Alex,

I just caught up with this issue now and I am looking at the server.

Sorry, but I don' understand, what do you mean?

Regarding the https. How was it installed? automatically or manually? I am
still starting to look, but I think there are some conf files missing

2017-10-28 21:49 GMT+02:00 Alexander Pico <notifications@github.com>:

**Comment by AlexanderPico** [comment]
Hi Nuno,

Manually.  As far as I can tell, the HTTPS is working fine.  A number of things have coincidentally broke and I'm trying to dissect them:

1. the jenkins test related to this particular issue stopped working, but that makes sense now because it was depending on a test dir on rcbranch that was blown out a few days ago. This needs to be fixed for the tests to work, but not actually related to HTTPS switch.

2. webservices stopped working. I just now figured out that there was an .htaccess file (not checked-in) that does the last crucial rewrite step. I've copied this to the new dir, checked it in, and now it works.  Also not related to HTTPS switch.

3. The Cytoscape and PV plugins for WikiPathways stopped working. Might be due to #2 or something else... Still checking. This one *might* actually be related to HTTPS swtich.

Your help in figuring these out and documenting would be appreciated. See email thread for latest...

**Comment by nunogit** [comment]
Hi Alex,

Yes, the .htaccess I  noticed. But i think there were also a few confs in
the apache virtual host configuration file.
It was not checked in kind of on purpose I think. That's kind of our
paritcular implementation / configuration. Not sure it should go into the
public repo.

2017-10-28 22:17 GMT+02:00 Alexander Pico <notifications@github.com>:

**Comment by AlexanderPico** [comment]
I agree the virtual host confs should not go in the repo. I tried to document them here as I figured them out today https://docs.google.com/document/d/16sYp5CkrqCl-GAgpZl27yixd5lzf8Zi4dEknm3iDCQQ/edit#heading=h.4rqqb4rgdgzx

I think that's the best we can do.

Which do you think are missing?  Again, the HTTPS and webservices are working now...  except via our plugins.

**Comment by nunogit** [comment]
Proxypass is doing a redirecttion instead of proxying. I think that's the
problem.
I am looking into it.

2017-10-28 22:27 GMT+02:00 Alexander Pico <notifications@github.com>:

**Comment by AlexanderPico** [comment]
Now I’m seeing an error that looks related to HTTPS :)

The PV plugin is throwing this error:

Error: The Pathway is not found
        java.rmi.RemoteException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target;


Caused by this line in out Utils.java: HttpResponse response = client.execute(httpget);
https://github.com/wikipathways/wikipathways-api-client-java/blob/master/org.wikipathways.client/src/org/wikipathways/client/utils/Utils.java#L58

**Comment by AlexanderPico** [comment]
Not sure why we need the ProxyPass anymore (now that everything is HTTPS)... getting rid of it might simplify and resolve security error we are seeing now, right?

**Comment by nunogit** [comment]
I think I solved the problem.

Getting rid of proxypass can definitly be something to think about. That
didn't happen before for legacy I think.

The issue was that before we were still supporting wikipathways both in
http and https.
Since now are redirecting all http to https proxying (reverse proxy) to
http leads to a redirect. In other word, http on reverse proxy needed to be
changed to https as in the example:

ProxyPass / http*s*://www.wikipathways.org/wpi/webservice2.0/
ProxyPassReverse / http*s*://www.wikipathways.org/wpi/webservice2.0/

The next issue is that reverse proxy by default does not support proxying
to https, so we needed to enable it, leading to this config:

*SSLProxyEngine on*

ProxyPass / https://www.wikipathways.org/wpi/webservice2.0/
ProxyPassReverse / https://www.wikipathways.org/wpi/webservice2.0/






2017-10-28 22:44 GMT+02:00 Alexander Pico <notifications@github.com>:

**Comment by AlexanderPico** [comment]
Nice! Both the Cytoscape and PV plugins work now. Can you please document how this works so the next time we have to set this up or troubleshoot it we can recall this decision and logic?

https://docs.google.com/document/d/16sYp5CkrqCl-GAgpZl27yixd5lzf8Zi4dEknm3iDCQQ/edit#heading=h.4rqqb4rgdgzx

Less urgent, but still broken are:
1. the direct link:  webservice.wikipathways.org
2. Swagger

**Comment by nunogit** [comment]
:) that should be simpler.

Regarding pathvisio. I tested. Searching worked well, but browse lead
Pathvisio to die. Maybe a local problem. Can someone test?

2017-10-28 23:25 GMT+02:00 Alexander Pico <notifications@github.com>:

**Comment by AlexanderPico** [comment]
Browse works for me.

<img width="810" alt="screen shot 2017-10-28 at 2 30 13 pm" src="https://user-images.githubusercontent.com/1418193/32138716-8899e200-bbec-11e7-95cc-7aaa2b935d0f.png">

**Comment by AlexanderPico** [comment]
Agreed. These final issues are less urgent (if you need to sleep :)...

**Comment by nunogit** [comment]
Thanks. I was still trying to do it, should be simple, but its taking a bit
longer than expected. Since this is no longer as urgent I will get some
rest and look at it first thing in the morning.


2017-10-28 23:31 GMT+02:00 Alexander Pico <notifications@github.com>:

**Comment by egonw** [comment]
Hi both, thanks for your hard work!

I also see that Swagger is still broken... I like to mention that that is something we specifically mention in the new WPNAR paper...

**Comment by nunogit** [comment]
Swagger is back on! :)
The solution is quite simple. Just a redirect. It needs be a strict
redirect though and with a few details that I will document.
I was trying some other fancy solutions but in the end  I think this was is
the best.

2017-10-29 0:12 GMT+02:00 Nuno M <nunomsilvanunes@gmail.com>:
